### ISSUE TITLE
Resource with Task works differently than with IO when cancelled

### ISSUE THREAD

**Issue by tkubicz** [monix/monix#1124]
Hello,
I've recently encountered a problem with `Resource` using `Task`. When cancelling the fibre, resource cancellation mechanics doesn't seem to obey the bracket laws. 

Please take a look at code examples with results below:

Lib versions:
monix-eval: 3.1.0
cats-core: 2.1.0
cats-effect: 2.1.1

Example code using `Task` (just replace TaskApp and Task with IOApp and IO for IO usage):
```scala
object ResourceTask extends TaskApp {

  override def run(args: List[String]): Task[ExitCode] = for {
    _ <- runProgram[Task]
    _ <- sleep[Task](10.seconds)
  } yield ExitCode.Success

  def runProgram[F[_] : Sync : Concurrent : Timer]: F[Unit] = {
    for {
      fiber <- resourceProgram[F].start
      _ <- sleep[F](5.seconds)
      _ <- fiber.cancel // Cancel the program during step 2 acquisition
      _ <- log[F]("Fiber has been cancelled")
    } yield ()
  }

  def resourceProgram[F[_] : Sync : Timer]: F[Unit] = {
    (for {
      _ <- Resource.make(log[F]("Step 1 acquire start") *> sleep[F](2.seconds) *> log[F]("Step 1 acquire stop"))(
        _ => log[F]("Step 1 release") *> sleep[F](2.seconds))
      _ <- Resource.make(log[F]("Step 2 acquire start") *> sleep[F](5.seconds) *> log[F]("Step 2 acquire stop"))(
        _ => log[F]("Step 2 release") *> sleep[F](5.seconds))
      _ <- Resource.make(log[F]("Step 3 acquire"))(_ => log[F]("Step 3 release"))
      _ <- Resource.make(log[F]("Step 4 acquire"))(_ => log[F]("Step 4 release"))
    } yield ()).allocated.flatMap(_._2)
  }

  def log[F[_] : Sync](message: String): F[Unit] = Sync[F].delay(println(message))

  def sleep[F[_] : Timer](duration: FiniteDuration): F[Unit] = Timer[F].sleep(duration)
}
```

Results using `Task`:
```
Step 1 acquire start
Step 1 acquire stop
Step 2 acquire start
Step 1 release
Fiber has been cancelled
Step 2 acquire stop
Step 2 release
Step 3 acquire
Step 3 release
Step 4 acquire
Step 4 release
```

Results using `IO`:
```
Step 1 acquire start
Step 1 acquire stop
Step 2 acquire start
Step 2 acquire stop
Step 2 release
Step 1 release
Fiber has been cancelled
```

In both examples, I'm cancelling the fibre during the acquisition phase of `Step 2`. According to `Bracket` laws, `acquire` in uncancellable which seems to work fine. But when using `Task` the `release` phase of `Step 1` is executed when `acquire` of step 2 is not finished yet. It should not happen because resource acquired during `Step 1` can still be used during `Step 2` acquisition.

The second issue I have is that after cancellation, `Step 3` and `Step 4` are still executed. It seems to work just fine when using `IO` instead of `Task`.

**Comment by Avasil** [comment]
Thanks for the report, I will look at it tomorrow and deal with it asap
It might be related to https://github.com/monix/monix/pull/1120 which was included in the cats-effect release but not yet in Monix

**Comment by Avasil** [comment]
@tkubicz I checked and indeed it is related to #1120 which fixes the reported issue - would you like a snapshot version before proper release?

**Comment by tkubicz** [comment]
Hi @Avasil, thanks for the quick response. I'd be much obliged, if you'd publish a snapshot version.

**Comment by Avasil** [comment]
@tkubicz No problem, I have just released `3.2.0-ea00da2-SNAPSHOT` from that branch - let me know if you find further issues/inconsistencies!

> thanks for the quick response

Well, I was just yesterday talking on a meetup how Monix stays consistent with Cats IO 😅

**Comment by tkubicz** [comment]
Hello @Avasil, the snapshot version that you've published seems to resolve the bracket/resource issue. I was able to successfully use it and everything looks ok.

However, there is another issue with this snapshot that doesn't appear in 3.1.0 - I'm not sure if the issue is with your recent changes or some other changes developed for 3.2.0 release. I'm receiving `Promise already completed` exception very often:

```
java.lang.IllegalStateException: Promise already completed.
    at scala.concurrent.Promise.complete(Promise.scala:57)
    at scala.concurrent.Promise.complete$(Promise.scala:56)
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
    at scala.concurrent.Promise.success(Promise.scala:91)
    at scala.concurrent.Promise.success$(Promise.scala:91)
    at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
    at monix.eval.internal.TaskConnection$Impl.$anonfun$cancel$11(TaskConnection.scala:161)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at monix.eval.internal.TaskRunLoop$.startLight(TaskRunLoop.scala:271)
    at monix.eval.Task.$anonfun$runAsyncUncancelableOpt$1(Task.scala:934)
    at monix.execution.misc.CanIsolateInstancesLevel0$SynchronousInstance$.bindContext(CanBindLocals.scala:115)
    at monix.execution.misc.CanBindLocals.isolate(CanBindLocals.scala:54)
    at monix.execution.misc.CanBindLocals.isolate$(CanBindLocals.scala:53)
    at monix.execution.misc.CanIsolateInstancesLevel0$SynchronousInstance$.isolate(CanBindLocals.scala:111)
    at monix.execution.misc.Local$.isolate(Local.scala:86)
    at monix.eval.Task.runAsyncUncancelableOpt(Task.scala:933)
    at monix.eval.Task.runAsyncAndForgetOpt(Task.scala:867)
    at monix.eval.Task.runAsyncAndForget(Task.scala:842)
    at monix.eval.internal.TaskRace$Register$$anon$2.onSuccess(TaskRace.scala:89)
    at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:165)
    at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:222)
    at monix.execution.schedulers.TracingRunnable.run(TracingRunnable.scala:33)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I'll try to write some code to be able to reproduce this exception. I'll create a new ticket for it when I'm done.

**Comment by Avasil** [comment]
It is probably the same PR, thank you for raising it! Reproducible example would be of course really helpful

I think it's ok to just post it here

**Comment by Avasil** [comment]
@tkubicz 

I didn't work on reproducing it but I have a hunch what could cause it

Could you try `3.2.0-863d081-SNAPSHOT`?

**Comment by tkubicz** [comment]
Hi @Avasil, your new snapshot version works much better. I wasn't able to reproduce the exception with this version.

**Comment by Avasil** [comment]
Awesome, thank you for testing it. :)
