### ISSUE TITLE
Iterant.fromReactivePublisher throws MatchError: null if completed before started

### ISSUE THREAD

**Issue by aakoshh** [monix/monix#1180]
We're transforming an `Observable` to an `Iterant` using `fromReactivePublisher`. Occasionally we got `MatchError: null` from [this](https://github.com/monix/monix/blob/3.0.0/monix-tail/shared/src/main/scala/monix/tail/internal/IterantFromReactivePublisher.scala#L119) line, meaning that the `state` of the `IterantSubscriber` is still null, I'm guessing because it ends before it has a chance to be started [here](https://github.com/monix/monix/blob/3.0.0/monix-tail/shared/src/main/scala/monix/tail/internal/IterantFromReactivePublisher.scala#L60). 

I tried to reproduce it in a test. Not sure if my test case is legit, but here goes:
```scala
package test.monix

import monix.eval.Task
import monix.execution.{Cancelable, Scheduler}
import monix.reactive.Observable
import monix.reactive.observers.Subscriber
import monix.tail.Iterant
import org.scalatest._
import scala.concurrent.duration._

class ObservableIterantSpec extends FlatSpec {

  import Scheduler.Implicits.global

  "Iterant.fromReactivePublisher" should "not have a race condition" in {
    val obs = new Observable[Nothing] {
      override def unsafeSubscribeFn(subscriber: Subscriber[Nothing]): Cancelable = {
        subscriber.onComplete()
        Cancelable.empty
      }
    }

    val it = Iterant.fromReactivePublisher[Task, Nothing](obs.toReactivePublisher)

    it.toListL.runSyncUnsafe(1.second)
  }
}
```

And the result:
```
scala.MatchError: null
	at monix.tail.internal.IterantFromReactivePublisher$IterantSubscriber.finish(IterantFromReactivePublisher.scala:119)
	at monix.tail.internal.IterantFromReactivePublisher$IterantSubscriber.onComplete(IterantFromReactivePublisher.scala:152)
	at monix.reactive.internal.rstreams.ReactiveSubscriberAsMonixSubscriber.$anonfun$onComplete$1(ReactiveSubscriberAsMonixSubscriber.scala:91)
	at monix.execution.Ack$AckExtensions$.syncOnContinue$extension(Ack.scala:117)
	at monix.reactive.internal.rstreams.ReactiveSubscriberAsMonixSubscriber.onComplete(ReactiveSubscriberAsMonixSubscriber.scala:91)
	at monix.reactive.observers.SafeSubscriber.$anonfun$onComplete$1(SafeSubscriber.scala:67)
	at monix.execution.Ack$AckExtensions$.syncOnContinue$extension(Ack.scala:117)
	at monix.reactive.observers.SafeSubscriber.onComplete(SafeSubscriber.scala:63)
	at test.monix.ObservableIterantSpec$$anon$1.unsafeSubscribeFn(ObservableIterantSpec.scala:18)
	at monix.reactive.Observable$$anon$2.subscribe(Observable.scala:3680)
  | => cat monix.tail.internal.IterantFromReactivePublisher$.$anonfun$apply$1(IterantFromReactivePublisher.scala:44)
	...
[info] - should not have a race condition *** FAILED *** (1 second, 206 milliseconds)
[info]   java.util.concurrent.TimeoutException: Task.runSyncUnsafe(1 second)

```

We're using Monix version 3.0.0

**Comment by aakoshh** [comment]
I applied [this](https://github.com/CasperLabs/CasperLabs/pull/1961/commits/5502108105776b4e111fffb4f302ee2d2abba1f0) workaround on a copy of `IterantFromReactivePublisher` to make it work. If you agree with it I'm happy to make a PR. The issue was that `acquire` calls `pub.subscribe(out)` but the `state` is only initialized later, so an early error or completion found `null`.

**Comment by alexandru** [comment]
@aakoshh a fix would be most welcome.

I wouldn't introduce an `Atomic` — we should just add a new state extending that sealed trait called `Uninitialised` and then deal with it in all pattern matches.

If not possible or too hard, then your fix is fine.

**Comment by aakoshh** [comment]
I'll have a look at doing that, cheers.
