### ISSUE TITLE
runtime failure on cats.effect.Clock dependency

### ISSUE THREAD

**Issue by TRReeve** [monix/monix#1510]
Hi all. 

I was looking to give monix a run integrating into some small parts of our database integrations. I add the dependency like so in gradle. 

`
  // https://mvnrepository.com/artifact/io.monix/monix
    implementation("io.monix:monix_2.13:3.4.0")`

And I've been trying to run a function that wraps a task in retry functionality. 

`class CassandraService(override val connector: CassandraConnection,
                       logger: Logger, monixScheduler: Scheduler)(implicit system: ActorSystem[_]) extends Database[CassandraService](connector) {

  def withCassandraBackoff[A](source: Task[A], attempt: Int =0, delay: FiniteDuration = 30.seconds): Task[A] = {
    source.onErrorHandleWith { ex =>
      val incrementAttempt = attempt + 1
      val jitter = Random.between(delay._1, delay._1 * 2)
      val randomDelay = jitter.seconds
      ex match {
        case writeTimeout: com.datastax.driver.core.exceptions.WriteTimeoutException =>
          logger.warn(s"Cassandra IO write failure attempt ${attempt + 1} failed due to ${writeTimeout.getMessage} restarting")

          withCassandraBackoff(source, incrementAttempt, randomDelay)
            .delayExecution(randomDelay)
        case _ =>
          Task.raiseError(ex)
      }
    }
  }
  
    def writePing(ping: Ping): CancelableFuture[Ping] = {
      val newPingFeature = PingFeatureset(ping)
      val writeNewPing = Task.parMap2(
        pingfeature.createNewPingFeatureset(newPingFeature),
        entityping.writeEntityPing(ping))((_, _) => newPingFeature)

      withCassandraBackoff(writeNewPing).map(_ => ping).runToFuture(monixScheduler)
    }`

The expected output is I run this to a future and the future then appears in the calling Akka Streams stream. But what I actually get is 

`java.lang.NoClassDefFoundError: cats/effect/Clock
        at com.analytics.app.integration.cassandra.CassandraService.writePing(CassandraService.scala:51)
        at com.analytics.processors.ProcessingFunctions$.$anonfun$ingestPings$1(ProcessingFunctions.scala:74)
        at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1428)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:819)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
        at akka.actor.ActorCell.invoke(ActorCell.scala:548)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: cats.effect.Clock
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 21 more
`

thus far I've tried various flavours of adding cats-effect and cats-core and different versions of Monix to see if I can make it work. But everytime it complains about cats.effect.Clock not being available at runtime even when I am able to import cats.effect.Clock fine in my code. I also have doobie in my code and I am suspicious on if perhaps that could be causing some sort of clash but I haven't found any large changes in cats that would cause these kinds of clashes and I would've thought they'd show up at compile time anyway.

**Comment by jchapuis** [comment]
Have you checked whether your cats-effect dependency gets evicted for the more recent 3.x series? I believe `Clock` lives in `cats.effect.kernel`  now

**Comment by agascon9** [comment]
Is this still the case? I'm experiencing precisely the same issue with Monix 3.4.1 and Cats Effect 3.3.14.
