### ISSUE TITLE
Observable throws NoSuchFieldException (via jctools) on Android

### ISSUE THREAD

**Issue by Taig** [monix/monix#269]
Only old models (Android 4.1) from Samsung and Huawei appear to be affected.

```
java.lang.ExceptionInInitializerError
        at monix.reactive.observers.buffers.SimpleBufferedSubscriber$.unbounded(SimpleBufferedSubscriber.scala:260)
        at monix.reactive.observers.buffers.BuildersImpl$class.synchronous(BuildersImpl.scala:54)
        at monix.reactive.observers.BufferedSubscriber$.synchronous(BufferedSubscriber.scala:92)
        at monix.reactive.internal.builders.CreateObservable.unsafeSubscribeFn(CreateObservable.scala:32)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connection$lzycompute(ConnectableObservable.scala:54)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connection(ConnectableObservable.scala:53)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connect(ConnectableObservable.scala:57)
        ...
Caused by: java.lang.ExceptionInInitializerError
        at org.jctools.queues.BaseMpscLinkedArrayQueue.<clinit>(BaseMpscLinkedArrayQueue.java:79)
        at monix.reactive.observers.buffers.SimpleBufferedSubscriber$.unbounded(SimpleBufferedSubscriber.scala:260)
        at monix.reactive.observers.buffers.BuildersImpl$class.synchronous(BuildersImpl.scala:54)
        at monix.reactive.observers.BufferedSubscriber$.synchronous(BufferedSubscriber.scala:92)
        at monix.reactive.internal.builders.CreateObservable.unsafeSubscribeFn(CreateObservable.scala:32)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connection$lzycompute(ConnectableObservable.scala:54)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connection(ConnectableObservable.scala:53)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connect(ConnectableObservable.scala:57)
        ...
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: theUnsafe
        at org.jctools.util.UnsafeAccess.<clinit>(UnsafeAccess.java:45)
        at org.jctools.queues.BaseMpscLinkedArrayQueue.<clinit>(BaseMpscLinkedArrayQueue.java:79)
        at monix.reactive.observers.buffers.SimpleBufferedSubscriber$.unbounded(SimpleBufferedSubscriber.scala:260)
        at monix.reactive.observers.buffers.BuildersImpl$class.synchronous(BuildersImpl.scala:54)
        at monix.reactive.observers.BufferedSubscriber$.synchronous(BufferedSubscriber.scala:92)
        at monix.reactive.internal.builders.CreateObservable.unsafeSubscribeFn(CreateObservable.scala:32)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connection$lzycompute(ConnectableObservable.scala:54)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connection(ConnectableObservable.scala:53)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connect(ConnectableObservable.scala:57)
        ...
Caused by: java.lang.NoSuchFieldException: theUnsafe
        at java.lang.Class.getDeclaredField(Class.java:631)
        at org.jctools.util.UnsafeAccess.<clinit>(UnsafeAccess.java:40)
        at org.jctools.queues.BaseMpscLinkedArrayQueue.<clinit>(BaseMpscLinkedArrayQueue.java:79)
        at monix.reactive.observers.buffers.SimpleBufferedSubscriber$.unbounded(SimpleBufferedSubscriber.scala:260)
        at monix.reactive.observers.buffers.BuildersImpl$class.synchronous(BuildersImpl.scala:54)
        at monix.reactive.observers.BufferedSubscriber$.synchronous(BufferedSubscriber.scala:92)
        at monix.reactive.internal.builders.CreateObservable.unsafeSubscribeFn(CreateObservable.scala:32)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connection$lzycompute(ConnectableObservable.scala:54)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connection(ConnectableObservable.scala:53)
        at monix.reactive.observables.ConnectableObservable$$anon$1.connect(ConnectableObservable.scala:57)
        ...
```

**Comment by alexandru** [comment]
@Taig thanks for the report. I found the problem ... back in older versions of Android, the field is not named `theUnsafe`. I guess this is what we get for playing with private APIs :-)

Here's the implementation of `sun.misc.Unsafe` for Android 2.3: https://android.googlesource.com/platform/libcore/+/gingerbread/luni/src/main/java/sun/misc/Unsafe.java#32

I'll release a fix tomorrow.

**Comment by alexandru** [comment]
Implementation is in master, to be released ...
