### ISSUE TITLE
Reporting ConcatMap.onNext implementation is invalid

### ISSUE THREAD

**Issue by ajaychandran** [monix/monix#364]
This is happening in a multi threaded context on a source ```Observable``` transformed with a ```flatScan``` followed by a ```flatMap```.

```scala
      // scan state contains a list of decoded values and the remainder bits
      src.flatScan(DecodeResult(List.empty[R], BitVector.empty)) {
        (prev, bits) =>
          val code = prev.remainder ++ bits
          // recursive decode yields a list of values and remainder
          decoder.decodeR(code).fold(
            err => if (strict) Observable.raiseError(StreamDecodeException(err, code)) else Observable(DecodeResult(List.empty[R], BitVector.empty)),
            result => Observable(result))
      }
      // flatten decoded list of values
      .flatMap(result => Observable.fromIterable(result.value))
```
**Note**
There seems to be some race condition in the processing of the first element. In some runs, the error is not encountered but the first element is not emitted. When the error does occur, it is always on the first element.

**Log**
```
opening usb adapter 067b:2303@002:051:002 ...
Thread[dev-11,5,main] 067b:2303@002:051:002 < BitVector(8 bits, 0x20)
Thread[dev-12,5,main] 067b:2303@002:051:002 < BitVector(152 bits, 0x5b4d616e75616c204275726e2043617264735d)
Thread[dev-13,5,main] 067b:2303@002:051:002 < BitVector(80 bits, 0x3c436172643a4b483e20)
java.lang.IllegalStateException: State Active(monix.execution.Cancelable.empty) in the Monix ConcatMap.onNext implementation is invalid, please send a bug report! See https://monix.io
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber.reportInvalidState(ConcatMapObservable.scala:332)
	at monix.reactive.internal.operators.ConcatMapObservable$ConcatMapSubscriber.onNext(ConcatMapObservable.scala:246)
	at monix.reactive.internal.operators.FlatScanObservable$$anon$1$$anon$2.onNext(FlatScanObservable.scala:84)
	at monix.reactive.internal.builders.IteratorAsObservable.monix$reactive$internal$builders$IteratorAsObservable$$fastLoop(IteratorAsObservable.scala:165)
	at monix.reactive.internal.builders.IteratorAsObservable.startLoop(IteratorAsObservable.scala:66)
	at monix.reactive.internal.builders.IteratorAsObservable.unsafeSubscribeFn(IteratorAsObservable.scala:45)
	at monix.reactive.internal.builders.IterableAsObservable.unsafeSubscribeFn(IterableAsObservable.scala:32)
	at monix.reactive.internal.operators.FlatScanObservable$$anon$1.liftedTree1$1(FlatScanObservable.scala:74)
	at monix.reactive.internal.operators.FlatScanObservable$$anon$1.onNext(FlatScanObservable.scala:70)
	at device.io.DebugObservable$$anon$1.onNext(DebugObservable.scala:27)
	at monix.reactive.observers.SafeSubscriber.liftedTree1$1(SafeSubscriber.scala:47)
	at monix.reactive.observers.SafeSubscriber.onNext(SafeSubscriber.scala:46)
	at device.io.AsyncSubscriber$$anonfun$onNext$1.apply(AsyncSubscriber.scala:15)
	at device.io.AsyncSubscriber$$anonfun$onNext$1.apply(AsyncSubscriber.scala:15)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by alexandru** [comment]
@ajaychandran that error can also happen in case the back-pressuring contract is violated (i.e. multiple `onNext` events happen that don't wait for the returned `Future[Ack]` on concatMap's internal subscriber.

Can you share your `src` with me?

**Comment by alexandru** [comment]
@ajaychandran also, you don't have the latest version. Please upgrade to the latest `2.3.0`.

In version `2.2.0` the implementation of `concatMap` was changed for optimisation purposes with a riskier version that uses `getAndSet`, benefiting from Java 8 platform intrinsics.

But since then at least 2 issues have been fixed:

- https://github.com/monix/monix/issues/321
- https://github.com/monix/monix/issues/335

**Comment by ajaychandran** [comment]
Thanks for the quick turn around @alexandru 

The back-pressure contract was being violated; introducing a ```BufferedSubscriber``` in the flow fixed the issue.

**Comment by alexandru** [comment]
@ajaychandran if you cannot control the source, then a `BufferedSubscriber` is the right approach.

You also have `ConcurrentSubject` (which wraps subjects with a `BufferedSubscriber`) and `Observable.create` (which gives you a buffered subscriber as well).

Please UPGRADE to the latest version!

Also see this document for more details about that contract if interested:
https://monix.io/docs/2x/reactive/observers.html

**Comment by ajaychandran** [comment]
Thanks. Upgraded to 2.3.0; was testing with 2.2.3.
