### ISSUE TITLE
IllegalStateException: State Active(monix.execution.CancelableFuture$Implementation) in the Monix MapTask.onNext implementation is invalid

### ISSUE THREAD

**Issue by kellerkindt** [monix/monix#374]
```
java.lang.IllegalStateException: State Active(monix.execution.CancelableFuture$Implementation@b5e279e) in the Monix MapTask.onNext implementation is invalid, please send a bug report! See https://monix.io
	at monix.reactive.internal.operators.MapTaskObservable$MapAsyncSubscriber.reportInvalidState(MapTaskObservable.scala:291)
	at monix.reactive.internal.operators.MapTaskObservable$MapAsyncSubscriber.onNext(MapTaskObservable.scala:225)
	at monix.reactive.internal.operators.MapOperator$$anon$1.onNext(MapOperator.scala:46)
	at monix.reactive.internal.operators.MapOperator$$anon$1.onNext(MapOperator.scala:46)
	at monix.reactive.internal.operators.MapTaskObservable$MapAsyncSubscriber$$anonfun$1.apply(MapTaskObservable.scala:130)
	at monix.reactive.internal.operators.MapTaskObservable$MapAsyncSubscriber$$anonfun$1.apply(MapTaskObservable.scala:128)
	at monix.eval.internal.Transformation$Fold.success(Transformation.scala:51)
	at monix.eval.internal.Transformation.apply(Transformation.scala:29)
	at monix.eval.internal.TaskRunLoop$.liftedTree1$1(TaskRunLoop.scala:193)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:193)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$$anonfun$6$$anon$4.run(Task.scala:1463)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Happened while fiddling around with some test code, so the code itself isn't great at all.
Scrapped together what effectively caused it:
```scala
private val frameNumberSubject                   = PublishToOneSubject[Int]()
val frameNumberObserver : Observer[Int]          = frameNumberSubject
val mats                : Observable[(Mat, Int)] = frameNumberSubject.share.map(getMat)

val grayMats: Observable[(Mat, Int)] = mats.map(p => (ToGreyImage(matPool, p._1), p._2))


showMats(mats,     viewCl).subscribe()
showMats(grayMats, viewGr).subscribe()

def showMats(observable: Observable[(Mat, Int)], view: ImageView): Observable[Unit] = {
  observable
    .mapAsync(1)(p => Task{p})
    .map(p => (toBgraMat(p._1), p._2))
    .map(p => (toImage(p._1), p._2))
    .mapAsync(1)(p => 
      Task{
        RunInFx{view.setImage(p._1)}
      }
    )
}
```

```scala
(0 until properties.frames).foreach(number => {
  try {
    capture.frameNumberObserver.onNext(number) match {
      case Continue => Continue
      case Stop => Stop
      case e => {
        logger.warn("Whot? "+e.getClass)
      }
    }
  } catch {
    case e: Throwable => e.printStackTrace()
  }
})
```

**Comment by alexandru** [comment]
Most commonly this error happens whenever you're not respecting the back-pressure protocol, as described at: https://monix.io/docs/2x/reactive/observers.html

I see a `PublishToOneSubject` being initialized, but I don't see any buffering, or any back-pressuring when you're doing `frameNumberObserver.onNext`.

**Comment by kellerkindt** [comment]
Thanks for the fast response. I added the missing `frameNumberObserver` definition. Its not a show stopping issue, it just appeared once while fiddling around with it. It could very well be caused by wrong usage.
I might report back if it appears more often and I suppose the usage to be correct.
