### ISSUE TITLE
StackOverflow on MVar put

### ISSUE THREAD

**Issue by Odomontois** [monix/monix#483]
I have following code
https://gist.github.com/Odomontois/c7cf55d86ee6d5923e5ad266ed9fc872

using `"io.monix" %% "monix-eval" % "3-0-0-M2"` and `-Xss2048k`

When LanguageStore.likeCount is above 1000 I'm having 
> java.lang.StackOverflowError
	at scala.collection.immutable.Queue.isEmpty(Queue.scala:75)
	at monix.execution.misc.AsyncVar$WaitForPut.dequeue(AsyncVar.scala:314)
	at monix.execution.misc.AsyncVar.unsafePut(AsyncVar.scala:111)
	at monix.execution.misc.AsyncVar$$anon$2.onValue(AsyncVar.scala:239)
	at monix.execution.misc.AsyncVar.unsafePut(AsyncVar.scala:111)
	at monix.execution.misc.AsyncVar$$anon$2.onValue(AsyncVar.scala:239)
        ...

This example was specifically created to measure performance of `MVar` 

Setting `-Xss4096` fix problem for `likeCount= 1000` but with `likeCount = 10000` there is SO again

**Comment by alexandru** [comment]
Thanks @Odomontois for the report, it does seem like a problem, will take a look and hopefully fix it in time for the next release.
