### ISSUE TITLE
Batch.fromAnyArray(Array[Int]) throws

### ISSUE THREAD

**Issue by alexandru** [monix/monix#620]
```scala
val array: Array[Int] = (0 until 1000).toArray

Batch.fromAnyArray(array)
// => java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Object;
// =>   at monix.tail.batches.Batch$.fromAnyArray(Batch.scala:176)
// =>   at monix.tail.batches.Batch$.fromAnyArray(Batch.scala:185)
// =>   at monix.tail.Playground$.<init>(Playground.scala:63)
```

The signature currently is:

```scala
def fromAnyArray[A](array: Array[_]): ArrayBatch[A]
```

Arrays on the JVM are reified. Thus a conversion is required in case `array.isInstanceOf[Array[AnyRef]] == false`.

**Comment by oleg-py** [comment]
A conversion? If I was operating on something like `Array[Byte]` for efficiency sake, I certainly wouldn't like a defensive copy to be made.

The better approach is probably to create a correct builder based on `array.getClass.getComponentType` similar to `ArrayBuilder.make`

**Comment by Avasil** [comment]
@alexandru @oleg-py 
Well, my first approach is just:
```scala
  def fromAnyArray[A](array: Array[_], offset: Int, length: Int): ArrayBatch[A] = {
  val ref = array match {
    case _: Array[AnyRef] =>
      new ArrayBatch[Any](array.asInstanceOf[Array[Any]], offset, length, arrayAnyBuilder)
    case primitive: Array[Byte] =>
      new ArrayBatch[Byte](primitive, offset, length, arrayByteBuilder)
    case primitive: Array[Short] =>
      new ArrayBatch[Short](primitive, offset, length, arrayShortBuilder)
    case primitive: Array[Char] =>
      new ArrayBatch[Char](primitive, offset, length, arrayCharBuilder)
    case primitive: Array[Int] =>
      new ArrayBatch[Int](primitive, offset, length, arrayIntBuilder)
    case primitive: Array[Long] =>
      new ArrayBatch[Long](primitive, offset, length, arrayLongBuilder)
    case primitive: Array[Float] =>
      new ArrayBatch[Float](primitive, offset, length, arrayFloatBuilder)
    case primitive: Array[Double] =>
      new ArrayBatch[Double](primitive, offset, length, arrayDoubleBuilder)
    case primitive: Array[Boolean] =>
      new ArrayBatch[Boolean](primitive, offset, length, arrayBooleanBuilder)
    case primitive: Array[Unit] =>
      new ArrayBatch[Unit](primitive, offset, length, arrayUnitBuilder)
  }

  ref.asInstanceOf[ArrayBatch[A]]
}
```
but that's super ugly
