### ISSUE TITLE
Error running tests on Windows

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#728]
When I try to run tests for `executionJVM` project on my Windows machine, I get the following output:

```
[error] org.scalameta.invariants.InvariantFailedException: invariant failed:
[error] when verifying ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)).==('\"')
[error] found that ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)) is not equal to '\"'
[error] where ScalametaTokenizer = scala.meta.internal.tokenizers.ScalametaTokenizer@1081d535
[error]         at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
[error]         at scala.meta.internal.tokenizers.ScalametaTokenizer.emitContents$1(ScalametaTokenizer.scala:222)
[error]         at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:231)
[error]         at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:276)
[error]         at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:31)
[error]         at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:287)
[error]         at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:21)
[error]         at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:10)
[error]         at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:183)
[error]         at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:183)
[error]         at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:140)
[error]         at scala.meta.internal.parsers.ScalametaParser$$anon$189.apply(ScalametaParser.scala:3465)
[error]         at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
[error]         at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:10)
[error]         at com.github.tkawachi.doctest.ScaladocExtractor$.extract(ScaladocExtractor.scala:16)
[error]         at com.github.tkawachi.doctest.ScaladocTestGenerator$.apply(ScaladocTestGenerator.scala:22)
[error]         at com.github.tkawachi.doctest.DoctestPlugin$.$anonfun$doctestScaladocGenTests$3(DoctestPlugin.scala:70)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at com.github.tkawachi.doctest.DoctestPlugin$.doctestScaladocGenTests(DoctestPlugin.scala:70)
[error]         at com.github.tkawachi.doctest.DoctestPlugin$.$anonfun$doctestGenSettings$12(DoctestPlugin.scala:129)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
sbt:monix-execution> [error] (doctestGenTests) org.scalameta.invariants.InvariantFailedException: invariant failed:
[error] when verifying ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)).==('\"')
[error] found that ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)) is not equal to '\"'
[error] where ScalametaTokenizer = scala.meta.internal.tokenizers.ScalametaTokenizer@1081d535
[error] Total time: 1 s, completed 26.09.2018 16:59:01
```

On my work MacOS laptop everything is fine.

/cc @jozic, @tkawachi

**Comment by Avasil** [comment]
During development on Windows I disable `doctest` plugin temporarily, probably better to report it directly on https://github.com/tkawachi/sbt-doctest

**Comment by olafurpg** [comment]
What version of Scalameta is doctest using? I believe we have fixed a related issue recently, Windows CR LF were the cause.

**Comment by olafurpg** [comment]
Opened https://github.com/tkawachi/sbt-doctest/pull/125 to improve parse error handling in doctest.
