### ISSUE TITLE
Sporadic scala.MatchError inside Task.timeoutTo

### ISSUE THREAD

**Issue by Z1kkurat** [monix/monix#908]
Sometimes `Task.timeout` fails with `scala.MatchError` with the following stacktrace.
```
scala.MatchError: null
	at monix.eval.Task.$anonfun$timeoutTo$1(Task.scala:2208)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:147)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:108)
	at monix.eval.internal.TaskRestartCallback$$anon$1.run(TaskRestartCallback.scala:128)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:146)
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:39)
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:65)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
	at monix.execution.schedulers.ExecutorScheduler.execute(ExecutorScheduler.scala:34)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:72)
	at monix.execution.Callback$Base.run(Callback.scala:244)
	at monix.eval.internal.TaskConnection$TrampolinedWithConn.run(TaskConnection.scala:227)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline$ResumeRun$1.run(Trampoline.scala:51)
	at monix.execution.internal.forkJoin.AdaptedForkJoinTask.exec(AdaptedForkJoinTask.scala:27)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

At first glance, the only place in code where MatchError could happen in `timeoutTo` is if `Task.race` produces `null`. 
I can't reproduce this case manually, as it happens rarely under some load on unknown conditions.

Environment:
Java:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
Scala:
2.12.8

Monix libraries in classpath: 
```
io.monix.monix_2.12-3.0.0-RC2
io.monix.monix-catnap_2.12-3.0.0-RC2
io.monix.monix-eval_2.12-3.0.0-RC2
io.monix.monix-execution_2.12-3.0.0-RC2
io.monix.monix-java_2.12-3.0.0-RC2
io.monix.monix-kafka-1x_2.12-1.0.0-RC2
io.monix.monix-reactive_2.12-3.0.0-RC2
io.monix.monix-tail_2.12-3.0.0-RC2
```

**Comment by Avasil** [comment]
Thanks for the report, are you able to see if it also happens in `3.0.0-RC3`? (monix-kafka Rc4)

**Comment by Z1kkurat** [comment]
I think I would have to update my production environment to `3.0.0-RC3` version which I am a bit afraid of for now :) Sadly, couldn't reproduce on test environment, maybe not enough load

**Comment by alexandru** [comment]
Hi @Z1kkurat,

This could be a contract violation of `Callback` in `Task.create` / `Task.async`.

Are you by any chance calling `calback.onSuccess` multiple times, concurrently?

**Comment by alexandru** [comment]
@Avasil this issue with the `null` value comes from `TaskRestartCallback`. We'll need to investigate.

@Z1kkura can you give us some minimal code we could use in testing? Any pointers would be appreciated.

**Comment by Z1kkurat** [comment]
@alexandru I'm afraid the only thing this code does is creating `AsyncSubject` and waiting for `firstL` with timeout, not much of a logic.
```
val subject = AsyncSubject.apply[Unit]()
subject.firstL.timeout(timeout)
```

**Comment by alexandru** [comment]
@Z1kkurat this helps a lot, thanks. We'll investigate.

**Comment by alexandru** [comment]
A test that does this at high load shouldn't be too hard to build.

**Comment by alexandru** [comment]
Hi @Z1kkurat,

I've forked `3.0.0-RC2` and made some relatively small changes on this branch, in order to identify the issue: https://github.com/monix/monix/pull/917

I've pushed a new test version with it: `3.0.0-RC2-cb74787` 
(synchronizing to Maven Central now)

I have a suspicion that this is a contract violation, but I couldn't reproduce your issue exactly as it is. Can you help us by trying out this intermediate version?

What this version does is to protect the `Callback` in `Task.create`. In case there's a contract violation and that callback gets called twice, then an `IllegalAccessException` will get thrown exactly where the violation happens. And `Task.create` itself should catch this exception and report it via the reporter in your used `Scheduler`.

**Comment by Z1kkurat** [comment]
I will try to use this version in the next few weeks, thanks!

**Comment by alexandru** [comment]
@Z1kkurat any updates on this issue?

Can you try testing the version that I've prepared in that ticket? (#917)

**Comment by arcolife** [comment]
seeing this as well

```
scala.MatchError: null
	at monix.tail.internal.IterantFromReactivePublisher$IterantSubscriber.finish(IterantFromReactivePublisher.scala:119)
	at monix.tail.internal.IterantFromReactivePublisher$IterantSubscriber.onComplete(IterantFromReactivePublisher.scala:152)
	at monix.reactive.internal.rstreams.ReactiveSubscriberAsMonixSubscriber.$anonfun$onComplete$1(ReactiveSubscriberAsMonixSubscriber.scala:91)
	at monix.execution.Ack$AckExtensions$.syncOnContinue$extension(Ack.scala:117)
	at monix.reactive.internal.rstreams.ReactiveSubscriberAsMonixSubscriber.onComplete(ReactiveSubscriberAsMonixSubscriber.scala:91)
	at monix.reactive.observers.SafeSubscriber.$anonfun$onComplete$1(SafeSubscriber.scala:67)
	at monix.execution.Ack$AckExtensions$.syncOnContinue$extension(Ack.scala:117)
	at monix.reactive.observers.SafeSubscriber.onComplete(SafeSubscriber.scala:63)
	at monix.reactive.internal.operators.DoOnErrorOperator$$anon$1.onComplete(DoOnErrorOperator.scala:34)
	at monix.reactive.internal.operators.UpstreamTimeoutObservable$$anon$1.onComplete(UpstreamTimeoutObservable.scala:128)
	at monix.reactive.internal.rstreams.AsyncSubscriberAsReactiveSubscriber$$anon$1.onComplete(SubscriberAsReactiveSubscriber.scala:153)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.signalComplete(SimpleBufferedSubscriber.scala:156)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.fastLoop(SimpleBufferedSubscriber.scala:236)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.run(SimpleBufferedSubscriber.scala:129)
	at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by alexandru** [comment]
We'll need further investigation then.

@arcolife what version are you using?

**Comment by Avasil** [comment]
@alexandru Note that it's most likely a different issue in `IterantFromReactivePublisher`

**Comment by aakoshh** [comment]
@Avasil @alexandru  I created a separate issue for what @arcolife reported https://github.com/monix/monix/issues/1180
Thanks
