### ISSUE TITLE
IllegalStateException in Task.mapBoth

### ISSUE THREAD

**Issue by Z1kkurat** [monix/monix#920]
Recently I've got a strange error, here's the stacktrace (removed  a couple of sensitive lines from the very end of it, hope it won't make any difference):  
```
Exception: java.lang.IllegalStateException: Left("result")
	at monix.eval.internal.TaskMapBoth$Register$$anon$1.onSuccess(TaskMapBoth.scala:115)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:143)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:108)
	at monix.eval.internal.TaskRestartCallback$$anon$1.run(TaskRestartCallback.scala:128)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:146)
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:39)
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:65)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
	at monix.execution.schedulers.ExecutorScheduler.execute(ExecutorScheduler.scala:34)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:72)
	at monix.eval.internal.TaskStart$StartForked.apply(TaskStart.scala:52)
	at monix.eval.internal.TaskStart$StartForked.apply(TaskStart.scala:37)
	at monix.eval.internal.TaskRestartCallback.start(TaskRestartCallback.scala:58)
	at monix.eval.internal.TaskRunLoop$.executeAsyncTask(TaskRunLoop.scala:564)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:115)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:108)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
	at monix.execution.Callback.apply(Callback.scala:55)
	at monix.eval.internal.TaskFromFuture$.$anonfun$startSimple$1(TaskFromFuture.scala:114)
	at monix.eval.internal.TaskFromFuture$.$anonfun$startSimple$1$adapted(TaskFromFuture.scala:114)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:146)
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:39)
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:65)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:94)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
	at akka.stream.impl.fusing.GraphStages$IgnoreSink$$anon$10.onUpstreamFinish(GraphStages.scala:425)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:500)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:374)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:47)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:43)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnComplete.execute(ActorGraphInterpreter.scala:72)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The only code that executes in around there and falls under my suspicion is the following one:
```scala
def limitedTraverse[F[_]: Concurrent: Paralleled, A, B](in: List[A], batchSize: Int)(
      f: A => F[B]
  ): F[List[B]] =
    for {
      semaphore <- Semaphore[F](batchSize.toLong)
      result <- in.parTraverse(value => semaphore.withPermit(f(value)))
    } yield result
```
Following from the code it points to, "This task has triggered multiple onSuccess calls violating the protocol. Should never happen". I did not call any callbacks manually, the only thing code did was calling function from above with relatively small `batchSize`(100).

Environment:
Java:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Scala:
2.12.8

Monix libraries in classpath:
```
io.monix.monix_2.12-3.0.0-RC2
io.monix.monix-catnap_2.12-3.0.0-RC2
io.monix.monix-eval_2.12-3.0.0-RC2
io.monix.monix-execution_2.12-3.0.0-RC2
io.monix.monix-java_2.12-3.0.0-RC2
io.monix.monix-kafka-1x_2.12-1.0.0-RC2
io.monix.monix-reactive_2.12-3.0.0-RC2
io.monix.monix-tail_2.12-3.0.0-RC2
```

**Comment by alexandru** [comment]
That `IllegalStateException` can only happen when somebody violates the protocol. In other words this here is not the fault of `Task.mapBoth`.

I will try reproducing this issue myself, as you're being very specific, but would appreciate if you helped us with the suggestion to try the snapshot, which might help us find the code that's responsible:

https://github.com/monix/monix/issues/908#issuecomment-504159629

I know this might pose problems for you, so I'm not insisting, but really hope that we'll get to the bottom of it.

**Comment by Avasil** [comment]
@Z1kkurat did you encounter this or #908 error since `3.0.0` if you had a chance to test it?
