### ISSUE TITLE
NullPointerException in CanBindLocals / Local.isolate?

### ISSUE THREAD

**Issue by alexandru** [monix/monix#991]
Shit, I think we have a problem in the latest release:

```
java.lang.NullPointerException
	at monix.execution.misc.CanBindLocals.isolate(CanBindLocals.scala:54)
	at monix.execution.misc.CanBindLocals.isolate$(CanBindLocals.scala:53)
	at monix.execution.misc.CanIsolateInstancesLevel0$SynchronousInstance$.isolate(CanBindLocals.scala:111)
	at monix.execution.misc.Local$.isolate(Local.scala:86)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:143)
	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$2(TaskRunLoop.scala:217)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at monix.execution.misc.CanIsolateInstancesLevel0$SynchronousInstance$.bindContext(CanBindLocals.scala:115)
	at monix.execution.misc.Local$.bind(Local.scala:94)
	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:215)
	at monix.execution.internal.InterceptableRunnable$Wrapped.run(InterceptableRunnable.scala:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by alexandru** [comment]
The bug seems to be thrown in:

```
  def isolate(f: => R): R =
    bindContext(Local.getContext().isolate())(f)
```

**Comment by alexandru** [comment]
But that's not necessarily the source.

**Comment by cemelo** [comment]
I saw this bug. Using a TracingScheduler made it work for me.

**Comment by alexandru** [comment]
@cemelo I've just released `3.0.0-RC5`. 

Can you please verify that it works, without the `TracingScheduler`?

**Comment by cemelo** [comment]
@alexandru Sure thing.

**Comment by cemelo** [comment]
@alexandru it worked, although it seems the requirement to enable local context propagation is back? Without it I get a contract violation error, even when I use a `TracingScheduler`.
